### ISSUE TITLE
unicorn.mem_map truncated 48 bit address

### ISSUE THREAD

**Issue by smeng9** [AlexAltea/unicorn.js#21]
Hello again,

When I tried to map the stack for 64 bit binary, for example 0x7fff ffff df20, and try to access the memory at that address later, I always get Invalid memory write for (UC_ERR_MEMORY_UNMAPPED) issue.

I believe the higher bits are truncated and it is actually mapped to 0xffffdf20 because I verified at that region we will not have memory read/write/fetch issue.

The root cause of the issue seems to be MUnicorn.ccall function address argument is always followed by 0, which wiped off the higher bits. Maybe we can try to divide address that are larger than 32 bits to two parts and pass the higher bits instead of 0.

PS: I will test the hooking issue soon.

**Comment by AlexAltea** [comment]
> The root cause of the issue seems to be MUnicorn.ccall function address argument is always followed by 0, which wiped off the higher bits. Maybe we can try to divide address that are larger than 32 bits to two parts and pass the higher bits instead of 0.

All these issues stem from the fact that JavaScript cannot handle 64-bit integers natively. We might need 64-bit integer emulation for the API similar to https://github.com/AlexAltea/libelf.js/blob/master/src/libelf-integers.js

For each wrapped function that might potentially accept 64-bit integers we could do a `typeof` to check whether the argument is a:
1. Number (<= 53-bits): If so, forward `[argument & 0xFFFFFFFF, argument >> 32]` (or the equivalent in JavaScript, integer operations can be tricky). This will raise the current limit from 32-bits to 53-bits (enough for non-PML5 x86 code).
2. Emulated 64-bit integer: If so, then unpack each half `[number.lo, number.hi]`.

Implementing the 1st case alone should fix your issue, since your address can still fit the 53-bit sign+mantissa of doubles used in JavaScript. Unfortunately, I don't have the time to do it myself right now, but I'll do my best answering any questions you might have about the wrappers.
