### ISSUE TITLE
Update Unicorn to v1.0.2

### ISSUE THREAD

**Issue by zengming00** [AlexAltea/unicorn.js#23]
Unicorn has released version 1.0.2, do you have any plans to upgrade this project?

**Comment by AlexAltea** [comment]
Unfortunately, I don't have time to update this wrapper. Pull requests are welcome though.

**Comment by smeng9** [comment]
Hi, Unicorn 1.0.2 made a lot of changes on the Makefile compared to 1.0.1. Especially they removed all options related to TCI and TCG. @AlexAltea do you know the reason why we have tci/tcg in the code? to reduce code size or something else?

Currently I have to comment out the function patchUnicornTCI() in build.py and additional patches for tci, softmmu rename object and header gen in patchUnicornJS() to make building for single architecture work in 1.0.2. After building, during runtime it will report RangeError: WebAssembly.Table.get() which I have no idea.

I am not a Makefile expert so I cannot get the combined libunicorn.a for all architecture compiled. However this can be a good starting point for someone interested.

**Comment by AlexAltea** [comment]
> Especially they removed all options related to TCI [...]

That's unfortunate. TCI is a TCG backend that allows interpreting TCG bytecode (which is the result of translating instructions). Think of it as an intermediate representation like LLVM IR, which then gets compiled to whatever host architecture you have.

The reason we need TCI, is because we cannot execute the host instructions that the `tcg/i386` backend generates.
On a browser we can only interpret the bytecode... or alternatively we could add a JS/WASM JIT backend. I've seen few attempts of that in the wild, and it might be a viable solution.
 
> and TCG.

It's not possible for Unicorn to remove TCG: they would be left out with accelerators only, which only supports execution of host instructions (through a virtual machine).
