### ISSUE TITLE
Got matchExpr[type].exec is not a function when using with jQuery

### ISSUE THREAD

**Issue by RossComputerGuy** [AlexAltea/unicorn.js#4]
Hey can this be fixed so I can use this with jQuery.

**Comment by AlexAltea** [comment]
@SpaceboyRoss01 The demos use Unicorn.js alongside jQuery 3.1.1 without any problems. Can you describe me your setup or provide an example where the error is replicated?

**Comment by RossComputerGuy** [comment]
I am using foundation (a ui framework) with jquery 3.1.1 in a chrome app

**Comment by AlexAltea** [comment]
@SpaceboyRoss01 The bug was fixed previously, but I forgot to upload the release builds. You can find the fixed version here: https://github.com/AlexAltea/unicorn.js/releases/tag/v1.0-rc3

Try it and let me know if it works.

**Comment by RossComputerGuy** [comment]
Takes forever to load sometimes, uses lots of memory. It crashes a lot from memory usage. Besides that, it works.

**Comment by AlexAltea** [comment]
> Takes forever to load sometimes

Depends on your connection. Make sure you are **not** linking to the Github releases (it's not meant to be a CDN). Also, if you only target one architecture make sure you are loading only *unicorn-...arch....min.js* rather than the huge *unicorn.min.js* file.

>  uses lots of memory

That's normal.

> It crashes a lot from memory usage.

That's not normal if your machine is relatively recent. File another issue if that's the case.

> Besides that, it works.

Good. I'm closing this.

**Comment by RossComputerGuy** [comment]
my computer is from this year, and the file is local
